version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
    - npm install -g handel
  build:
    commands:
    - handel deploy -e $ENVS_TO_DEPLOY -c $HANDEL_ACCOUNT_CONFIG -t handel-codepipeline-name=$PIPELINE_NAME
