version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
    - npm install -g handel
  build:
    commands:
    - handel delete -e $ENVS_TO_DELETE -c $HANDEL_ACCOUNT_CONFIG -y
